### ISSUE TITLE
Diagram ordening

### ISSUE THREAD

**Issue by damian1997** [martendebruijn/real-time-web-1920#3]
Hoe de diagram nu geordend is staat de Api links en de client rechts, dit zou je eigenlijk beter om kunnen draaien omdat je vanuit de client de interactie met de applicatie start en mensen het diagram van links naar rechts lezen. (yet again moet ik ook nog doen. ^^)

**Comment by martendebruijn** [comment]
Ik heb het diagram aangepast!
